trigger:
- main
- feature/initial-release

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: 5.x
- task: gitversion/execute@0
  displayName: Determine Version
- task: Docker@2
  displayName: Login to Registry
  inputs:
    command: login
    containerRegistry: Docker Hub
- script: curl -o ./src/.devcontainer/library/powershell-debian.sh https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/powershell-debian.sh
  displayName: Download PowerShell install script
- script: echo $DEVCONTAINER_VERSION > ./src/.devcontainer/library/VERSION
  displayName: Create VERSION file
  env:
    DEVCONTAINER_VERSION: $(GitVersion.FullSemVer)
- script: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  displayName: Set up QEMU
- script: docker buildx create --use
  displayName: Set up docker buildx
- task: DevcontainersCi@0
  inputs:
    subFolder: src
    imageName: natescherer/sre-devcontainer
    runCmd: python /opt/sredevcontainer/get_tool_versions.py