name: 'build' 
on:
  pull_request:
  push:
    branches:
      - main
      - feature/initial-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: 5.x
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download PowerShell install script
        uses: carlosperate/download-file-action@v1
        with:
          file-url: https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/powershell-debian.sh
          location: ./src/.devcontainer/library
      - name: Create VERSION file
        run: echo $DEVCONTAINER_VERSION > ./src/.devcontainer/library/VERSION
        env:
          DEVCONTAINER_VERSION: ${{ steps.gitversion.outputs.FullSemVer }}
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v1
        with:
          use: true
      - name: Build and release devcontainer Single-Platform
        uses: natescherer/devcontainers-ci@feature/multiple-architectures
        with:
          subFolder: src
          imageName: ghcr.io/natescherer/sre-devcontainer
          cacheFrom: ghcr.io/natescherer/sre-devcontainer:latest
          runCmd: python /opt/sredevcontainer/get_tool_versions.py
      # - name: Build and release devcontainer Multi-Platform
      #   uses: natescherer/devcontainers-ci@feature/multiple-architectures
      #   with:
      #     subFolder: src
      #     imageName: ghcr.io/natescherer/sre-devcontainer
      #     cacheFrom: ghcr.io/natescherer/sre-devcontainer:latest
      #     platform: linux/amd64,linux/arm64
      #     runCmd: python /opt/sredevcontainer/get_tool_versions.py
      # - name: Write version info to file
      #   uses: devops-actions/json-to-file@v1.0.0
      #   with:
      #     json: ${{ steps.buildcontainer.outputs.runCmdOutput }}
      #     filename: tool-versions.json
      # # Figure out how to make a table here
      # - run: echo "${{ steps.buildcontainer.outputs.runCmdOutput }}"
