name: 'build' 
on:
  pull_request:
  push:
    branches:
      - main
      - feature/initial-release
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: 5.x
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create VERSION file
        run: echo $DEVCONTAINER_VERSION > ./src/.devcontainer/library/VERSION
        env:
          DEVCONTAINER_VERSION: ${{ steps.gitversion.outputs.FullSemVer }}
      - name: Determine Version Sets for Multi-Version Tools
        run: |
          export KUBECTL_VERS=$(curl --request GET --url https://endoflife.date/api/kubernetes.json --header 'Accept: application/json' -sS | yq '.[] | select(.eol > now) | .cycle |= sub("^", "kubectl:") | .cycle' | xargs)
          export PYTHON_VERS=$(curl --request GET --url https://endoflife.date/api/python.json --header 'Accept: application/json' -sS | yq '.[] | select(.eol > now) | .cycle' | xargs)
          yq -i '.features."ghcr.io/natescherer/devcontainers-custom-features/hypermodern-python:1".versions = env(PYTHON_VERS)' src/.devcontainer/devcontainer.json -oj
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v2
      # - name: Build and release devcontainer Single-Platform
      #   id: buildcontainer
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     subFolder: src
      #     imageName: ghcr.io/natescherer/sre-devcontainer
      #     runCmd: python /opt/sredevcontainer/get_tool_versions.py
      - name: Build and release devcontainer Multi-Platform
        id: buildcontainer
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          subFolder: src
          imageName: ghcr.io/natescherer/sre-devcontainer
          platform: linux/amd64,linux/arm64
          # runCmd: python /opt/sredevcontainer/get_tool_versions.py
      # - name: Write version info to file
      #   uses: devops-actions/json-to-file@v1.0.0
      #   with:
      #     json: ${{ steps.buildcontainer.outputs.runCmdOutput }}
      #     filename: tool-versions.json
      # - name: Post Tool Versions as Check Run
      #   uses: LouisBrunner/checks-action@v1.5.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     name: Tool Version Report
      #     conclusion: neutral
      #     output: |
      #       {"summary": "Tool Version Report"}
      #     output_text_description_file: tool-versions.json
      # # Figure out how to make a table here
      # - run: echo "${{ steps.buildcontainer.outputs.runCmdOutput }}"
